const express=require('express');const http=require('http');const {Server}=require('socket.io');const path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,'public')));const rooms={};
const code=()=>Math.random().toString(36).slice(2,6).toUpperCase(),clean=s=>String(s||'').trim().slice(0,24);
const active=r=>r.cells.filter(c=>c.owner&&!c.dropped);
function pub(r){return {code:r.code,title:r.title,host:r.host,status:r.status,prize:r.prize,round:r.round,cells:r.cells,players:r.players,winner:r.winner,log:r.log.slice(-15)}}
function emit(r){io.to(r.code).emit('state',pub(r))} function log(r,msg){r.log.push(msg)}
function check(r){const a=active(r);if(a.length===1){r.winner={n:a[0].n,name:a[0].ownerName};r.status='finished';log(r,`#${a[0].n} — ${a[0].ownerName} IS THE LAST SPOT STANDING!`)}}
io.on('connection',s=>{
s.on('create',({name,title,size,prize},cb)=>{let c;do c=code();while(rooms[c]);let z=Math.max(10,Math.min(100,+size||30));rooms[c]={code:c,host:s.id,title:clean(title)||'LOCK-D-IN LIVE',status:'lobby',prize:clean(prize)||'Prize TBA',round:1,winner:null,log:[],cells:Array.from({length:z},(_,i)=>({n:i+1,owner:null,ownerName:null,dropped:false})),players:[{id:s.id,name:clean(name)||'Host',spot:null}]};s.join(c);log(rooms[c],`${clean(name)||'Host'} opened the board.`);cb({ok:true,code:c});emit(rooms[c])});
s.on('join',({name,code:c},cb)=>{c=clean(c).toUpperCase();const r=rooms[c];if(!r)return cb({ok:false,msg:'Room not found.'});if(r.status==='finished')return cb({ok:false,msg:'This round has ended.'});const nm=clean(name)||'Player';r.players.push({id:s.id,name:nm,spot:null});s.join(c);log(r,`${nm} pulled up.`);cb({ok:true,code:c});emit(r)});
s.on('claim',({code:c,n},cb)=>{const r=rooms[clean(c).toUpperCase()];if(!r||r.status!=='lobby')return cb({ok:false,msg:'Locks are closed.'});const p=r.players.find(x=>x.id===s.id),cell=r.cells.find(x=>x.n===+n);if(!p||!cell||cell.owner)return cb({ok:false,msg:'That spot is already locked.'});if(p.spot){const old=r.cells.find(x=>x.n===p.spot);if(old){old.owner=null;old.ownerName=null}}cell.owner=s.id;cell.ownerName=p.name;p.spot=cell.n;log(r,`${p.name} LOCK'D IN #${cell.n}.`);emit(r);cb({ok:true})});
s.on('start',c=>{const r=rooms[clean(c).toUpperCase()];if(!r||r.host!==s.id||active(r).length<2)return;r.status='live';log(r,'LOCKS CLOSED. We are LIVE.');emit(r)});
s.on('drop',({code:c,count},cb)=>{const r=rooms[clean(c).toUpperCase()];if(!r||r.host!==s.id||r.status!=='live'||r.winner)return;let k=Math.max(1,Math.min(20,+count||1));while(k-->0&&active(r).length>1){const a=active(r),x=a[Math.floor(Math.random()*a.length)];x.dropped=true;log(r,`#${x.n} — ${x.ownerName} — DROPPED ❌`)}check(r);emit(r)});
s.on('newRound',c=>{const r=rooms[clean(c).toUpperCase()];if(!r||r.host!==s.id)return;r.status='lobby';r.round++;r.winner=null;r.cells.forEach(x=>{x.owner=null;x.ownerName=null;x.dropped=false});r.players.forEach(p=>p.spot=null);log(r,`ROUND ${r.round} — BOARD OPEN. LOCK IN.`);emit(r)});
s.on('disconnect',()=>{for(const c of Object.keys(rooms)){const r=rooms[c],p=r.players.find(x=>x.id===s.id);if(!p)continue;if(r.status==='lobby'&&p.spot){const x=r.cells.find(q=>q.n===p.spot);if(x){x.owner=null;x.ownerName=null}}r.players=r.players.filter(x=>x.id!==s.id);if(!r.players.length){delete rooms[c];continue}if(r.host===s.id)r.host=r.players[0].id;emit(r)}})
});server.listen(process.env.PORT||3000,()=>console.log('LOCK-D-IN LIVE running'));